### ISSUE TITLE
Back button not functioning

### ISSUE THREAD

**Issue by YPITDataOmar** [oTranscribe/oTplayer#1]
I was trying out the demo provided to see how things work and saw that the BACK button does not move the player back the 1.5 seconds like suggested, but rather moves it forward like the FORWARD button does.  Not sure how/where to remedy this, but would be great if someone could provide some insight on how to fix.

**Comment by ejb** [comment]
61a6611 should have fixed this bug. Thanks for flagging!

Btw, just to warn you -- this module is likely to be deprecated in the near future, as oTranscribe 2 does not use it.
